GROQ_API_KEY = "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"
MONGO_URI = "mongodb://localhost:27017/mental_health_db"
YOUTUBE_API_KEY = "AIzaSyCXF_4_9F4FDzN5u9WEuNQZFkcNzH6mYVs"



POSTGRES_DB = "mental_health_db"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "1906"
POSTGRES_HOST = "localhost"  # Or your server IP if remote
POSTGRES_PORT = "5432"