GROQ_API_KEY = "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"
MONGO_URI = "mongodb://localhost:27017/mental_health_db"
YOUTUBE_API_KEY = "AIzaSyCXF_4_9F4FDzN5u9WEuNQZFkcNzH6mYVs"
OPENAI_API_KEY = "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"

POSTGRES_DB = "mental_health_db"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "1906"
POSTGRES_HOST = "localhost"  # Or your server IP if remote
POSTGRES_PORT = "5432"